### ISSUE TITLE
Unhandled Exception: MissingPluginException(

### ISSUE THREAD

**Issue by pp2015jp** [rodydavis/flutter_midi#22]
Dear Sir

Any idea for...

E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: MissingPluginException(No implementation found for method play_midi_note on channel flutter_midi)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
    <asynchronous suspension>
    #1      FlutterMidi.playMidiNote (package:flutter_midi/flutter_midi.dart:69)
    <asynchronous suspension>
    #2      _MyAppState._play (package:melody/main.dart:552)
    <asynchronous suspension>

**Comment by RaulUrtecho** [comment]
I got your same error message, I just used the `_flutterMidi.playMidiNote` method and debugging deeper (myCode + package) I got this exception:

`Unhandled Exception: PlatformException (error, attempt to invoke interface method 'void jp.kshoji.javax.sound.midi.Receiver.send (jp.kshoji.javax.sound.midi.MidiMessage, long)' on a reference of null, null object, java.lang.NullPointerException: Attempt to invoke interface method 'void jp.kshoji.javax.sound.midi.Receiver.send (jp.kshoji.javax.sound.midi.MidiMessage, long)' on a null object reference`


I hope @rodydavis will solve this bug soon.

**Comment by qianxuechao** [comment]
http://blog.z7ge.com/archives/flutter-missingpluginexception-bu-yao-huang 希望能帮到你

**Comment by rodydavis** [comment]
fixed on version `1.1.0`. reopen if it is still an issue

**Comment by GattoExpress999** [comment]
Yes it's still an issue and it's 2024

```
E/flutter (15750): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method unmute on channel flutter_midi)
E/flutter (15750): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (15750): <asynchronous suspension>
E/flutter (15750): #1      FlutterMidi.unmute (package:flutter_midi/flutter_midi.dart:51:27)
E/flutter (15750): <asynchronous suspension>
E/flutter (15750): 
E/flutter (15750): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method prepare_midi on channel flutter_midi)
E/flutter (15750): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (15750): <asynchronous suspension>
```

**Comment by rodydavis** [comment]
Happy to accept PRs!
