### ISSUE TITLE
The plugin `flutter_midi` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by Kizat** [rodydavis/flutter_midi#35]
The plugin `flutter_midi` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by rodydavis** [comment]
Im open to PRs!

**Comment by Kizat** [comment]
can help create a new flutter project and paste all the old code there?

**Comment by ifredom** [comment]
Is there an example to solve this problem? I really don't know Android

**Comment by weelion** [comment]
Yes, I am based on Android's official documentation. Try to solve this dependency problem of Android Embedding. But I don't have time to submit it.

Currently it works normally in my project.
